language: go
go:
- 1.21.x
before_install:
- openssl aes-256-cbc -K $encrypted_2d8c63ef40a5_key -iv $encrypted_2d8c63ef40a5_iv
  -in id_rsa.enc -out ../id_rsa -d
- chmod 600 ../id_rsa
- echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
- go get -t -v ./...
script:
- go test -v ./...
after_success:
- export VERSION=$(git rev-parse --short HEAD)
- rsync -rave "ssh -i ../id_rsa" --exclude=node_modules . $DEPLOY_USER@$DEPLOY_SERVER:~/blog-backend
- ssh -i ../id_rsa $DEPLOY_USER@$DEPLOY_SERVER "nohup mkdir -p blog-backend && cd blog-backend && export VERSION='$VERSION' && docker build --build-arg VERSION=$VERSION -t bloomingflower/blog-backend:$VERSION . && docker tag bloomingflower/blog-backend:$VERSION bloomingflower/blog-backend:latest && docker push bloomingflower/blog-backend && rm -rf dist > /dev/null 2>&1 &"
